function sysWR2a0 = a0Funct(J1,L1,g,inforce,m0,m1,pendvel,pendpos)
%a0Funct
%    sysWR2a0 = a0Funct(J1,L1,G,INFORCE,M0,M1,PENDVEL,PENDPOS)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Feb-2023 08:16:08

t2 = cos(pendpos);
t3 = sin(pendpos);
t4 = L1.^2;
t5 = m1.^2;
t6 = pendvel.^2;
sysWR2a0 = (J1.*inforce.*8.0+inforce.*m1.*t4.*2.0+L1.^3.*t3.*t5.*t6+J1.*L1.*m1.*t3.*t6.*4.0-g.*t2.*t3.*t4.*t5.*2.0)./(J1.*m0.*8.0+J1.*m1.*8.0+t4.*t5.*2.0-t2.^2.*t4.*t5.*2.0+m0.*m1.*t4.*2.0);
