function sysWR2u1 = u1Funct(J1,L1,g,inforce,m0,m1,pendvel,pendpos)
%u1Funct
%    sysWR2u1 = u1Funct(J1,L1,G,INFORCE,M0,M1,PENDVEL,PENDPOS)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Feb-2023 08:16:08

t2 = cos(pendpos);
t3 = sin(pendpos);
t4 = L1.^2;
t5 = m1.^2;
sysWR2u1 = -(L1.*m1.*(inforce.*t2.*2.0-g.*m0.*t3.*2.0-g.*m1.*t3.*2.0+L1.*m1.*pendvel.^2.*t2.*t3))./(J1.*m0.*4.0+J1.*m1.*4.0+t4.*t5-t2.^2.*t4.*t5+m0.*m1.*t4);
